name: Build for Windows

on:
  push:
    tags:
      - 'v*'  # Only runs when you push a version tag like v1.0
  workflow_dispatch:  # Also allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile
      run: |
        cl /EHsc wWinMain.cpp UnsavouryAutoSave.rc user32.lib gdi32.lib

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Unsavoury Auto Save 1.0
        path: wWinMain.exe
